name: Section_KA

on:
  schedule:
    - cron: "31 0,8 */6 * *"
  watch:
    types: started
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.private }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install requirements
        run: |
          pip install -r requirements.txt
          playwright install --with-deps chromium
      
      - name: Section_KA
        run: python3 section.py
        env:
          SEC_TION: ${{ secrets.SEC_TION }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
         
